development:
    dialect: postgres
    datasource: host=${DB_HOST} dbname=${DB_NAME} user=${DB_USERNAME} password=${DB_PASSWORD} sslmode=${DB_SSL_MODE}
    dir: /migrations
    table: migrations

production:
    dialect: postgres
    datasource: host=${DB_HOST} dbname=${DB_NAME} user=${DB_USERNAME} password=${DB_PASSWORD} sslmode=${DB_SSL_MODE}
    dir: /migrations
    table: migrations
